import { WALLET } from '@/config/constant'
import { IFRAME_GAME_URLS } from '@/config/page-url'
const { LODE, LODE_SIEUTOC, LOTTERY_CYBER_PUNK, LOTTERY_LAS_VEGAS } = IFRAME_GAME_URLS

export const gameFeature = {
  title: 'Long Quy Chi Bảo',
  imgSrc: require('~imageAsset/lobby/game-center-item/slot/long-quy-chi-bao.png'),
  loginRequired: true,
  gameId: 'kts9980',
  jackpot: true,
  provider: 'Techplay',
  newTab: true,
  promotionPrevent: false,
  wallet: WALLET.SUB,
  feature: true,
  gameType: 'gp_url'
}

const lobbyGame = {
  hotgame: [],
  slot: [
    {
      title: 'Long Quy Chi Bảo',
      imgSrc: require('~imageAsset/lobby/game-center-item/slot/long-quy-chi-bao.png'),
      loginRequired: true,
      gameId: 'kts9980',
      jackpot: true,
      provider: 'Techplay',
      newTab: true,
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'gp_url'
    },
    {
      title: 'Biệt Đội Mỹ Nữ',
      imgSrc: require('~imageAsset/lobby/game-center-item/slot/biet-doi-my-nu.png'),
      loginRequired: true,
      gameId: 'kts9996',
      jackpot: true,
      provider: 'Techplay',
      newTab: true,
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'gp_url'
    },
    {
      title: 'Ma Đao Lệ Ảnh',
      imgSrc: require('~imageAsset/lobby/game-center-item/slot/ma-dao-le-anh.png'),
      loginRequired: true,
      gameId: 'kts9984',
      jackpot: true,
      provider: 'Techplay',
      newTab: true,
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'gp_url'
    },
    {
      title: 'The Witcher',
      imgSrc: require('~imageAsset/lobby/game-center-item/slot/the-witcher.png'),
      loginRequired: true,
      gameId: 'kts9985',
      jackpot: true,
      provider: 'Techplay',
      newTab: true,
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'gp_url'
    },
    {
      title: 'Tứ Linh Thần Thú',
      imgSrc: require('~imageAsset/lobby/game-center-item/slot/tu-linh-than-thu.png'),
      loginRequired: true,
      gameId: 'kts9991',
      jackpot: true,
      provider: 'Techplay',
      newTab: true,
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'gp_url'
    },
    {
      title: 'Đường Tới Qatar',
      imgSrc: require('~imageAsset/lobby/game-center-item/slot/duong-den-qatar.png'),
      loginRequired: true,
      gameId: 'kts9982',
      jackpot: true,
      provider: 'Techplay',
      newTab: true,
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'gp_url'
    },
    {
      title: 'Thần Lực Bóng Tối',
      imgSrc: require('~imageAsset/lobby/game-center-item/slot/than-luc-bong-toi.png'),
      loginRequired: true,
      gameId: 'kts9989',
      jackpot: true,
      provider: 'Techplay',
      newTab: true,
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'gp_url'
    },
    {
      title: 'Aladdin',
      imgSrc: require('~imageAsset/lobby/game-center-item/slot/aladin.png'),
      loginRequired: true,
      gameId: 'kts9976',
      jackpot: true,
      provider: 'Techplay',
      newTab: true,
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'gp_url'
    },
    {
      title: 'Thanh Xà Bạch Xà',
      imgSrc: require('~imageAsset/lobby/game-center-item/slot/thanh-xa-bach-xa.jpg'),
      loginRequired: true,
      gameId: 'kts9994',
      jackpot: true,
      provider: 'Techplay',
      newTab: true,
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'gp_url'
    },
    {
      title: 'Thằng Bờm',
      imgSrc: require('~imageAsset/lobby/game-center-item/slot/thang-bom.jpg'),
      loginRequired: true,
      gameId: 'kts9997',
      jackpot: true,
      provider: 'Techplay',
      newTab: true,
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'gp_url'
    },
    {
      title: 'Tam Quốc Tranh Hùng',
      imgSrc: require('~imageAsset/lobby/game-center-item/slot/tam-quoc-tranh-hung.png'),
      loginRequired: true,
      gameId: 'kts9992',
      jackpot: true,
      provider: 'Techplay',
      newTab: true,
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'gp_url'
    },
    {
      title: 'Sơn Tinh Thủy Tinh',
      imgSrc: require('~imageAsset/lobby/game-center-item/slot/son-tinh-thuy-tinh.png'),
      loginRequired: true,
      gameId: 'kts9999',
      jackpot: true,
      provider: 'Techplay',
      newTab: true,
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'gp_url'
    },
    {
      title: 'Metal Gear Solid',
      imgSrc: require('~imageAsset/lobby/game-center-item/slot/metal-gear-solid.png'),
      loginRequired: true,
      gameId: 'kts9977',
      jackpot: true,
      provider: 'Techplay',
      newTab: true,
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'gp_url'
    },
    {
      title: 'Bí Mật Cleopatra',
      imgSrc: require('~imageAsset/lobby/game-center-item/slot/cleopatra.png'),
      loginRequired: true,
      gameId: 'kts9988',
      jackpot: true,
      provider: 'Techplay',
      newTab: true,
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'gp_url'
    },
    {
      title: 'Call Of War',
      imgSrc: require('~imageAsset/lobby/game-center-item/slot/call-of-war.png'),
      loginRequired: true,
      gameId: 'kts9979',
      jackpot: true,
      provider: 'Techplay',
      newTab: true,
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'gp_url'
    },
    {
      title: 'Honey Trap of Diao Chan',
      imgSrc: require('~imageAsset/lobby/game-center-item/pg-soft/honey-trap-of-diao-chan.png'),
      loginRequired: true,
      gameId: '1',
      gameCode: 'diaochan',
      jackpot: true,
      newTab: true,
      provider: 'PGSoft',
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'pg_url'
    },
    {
      title: 'Fortune Gods',
      imgSrc: require('~imageAsset/lobby/game-center-item/pg-soft/fortune-gods.png'),
      loginRequired: true,
      gameId: '3',
      gameCode: 'fortune-gods',
      jackpot: true,
      newTab: true,
      provider: 'PGSoft',
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'pg_url'
    },
    {
      title: 'Win Win Won',
      imgSrc: require('~imageAsset/lobby/game-center-item/pg-soft/win-win-won.png'),
      loginRequired: true,
      gameId: '24',
      gameCode: 'win-win-won',
      jackpot: true,
      newTab: true,
      provider: 'PGSoft',
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'pg_url'
    },
    {
      title: 'Medusa II',
      imgSrc: require('~imageAsset/lobby/game-center-item/pg-soft/medusa-II.png'),
      loginRequired: true,
      gameId: '6',
      gameCode: 'medusa2',
      jackpot: true,
      newTab: true,
      provider: 'PGSoft',
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'pg_url'
    },
    {
      title: 'Tree of Fortune',
      imgSrc: require('~imageAsset/lobby/game-center-item/pg-soft/tree-of-fortune.png'),
      loginRequired: true,
      gameId: '26',
      gameCode: 'fortune-tree',
      jackpot: true,
      newTab: true,
      provider: 'PGSoft',
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'pg_url'
    },
    {
      title: 'Medusa',
      imgSrc: require('~imageAsset/lobby/game-center-item/pg-soft/medusa.png'),
      loginRequired: true,
      gameId: '7',
      gameCode: 'medusa',
      jackpot: true,
      newTab: true,
      provider: 'PGSoft',
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'pg_url'
    },
    {
      title: 'Plushie Frenzy',
      imgSrc: require('~imageAsset/lobby/game-center-item/pg-soft/plushie-frenzy.png'),
      loginRequired: true,
      gameId: '25',
      gameCode: 'plushie-frenzy',
      jackpot: true,
      newTab: true,
      provider: 'PGSoft',
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'pg_url'
    },
    {
      title: 'Wizdom Wonders',
      imgSrc: require('~imageAsset/lobby/game-center-item/pg-soft/wizdom-wonders.png'),
      loginRequired: true,
      gameId: '17',
      gameCode: 'wizdom-wonders',
      jackpot: true,
      newTab: true,
      provider: 'PGSoft',
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'pg_url'
    },
    {
      title: 'Gem Saviour',
      imgSrc: require('~imageAsset/lobby/game-center-item/pg-soft/gem-saviour.png'),
      loginRequired: true,
      gameId: '2',
      gameCode: 'gem-saviour',
      jackpot: true,
      newTab: true,
      provider: 'PGSoft',
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'pg_url'
    },
    {
      title: 'Hood vs Wolf',
      imgSrc: require('~imageAsset/lobby/game-center-item/pg-soft/hood-vs-wolf.png'),
      loginRequired: true,
      gameId: '18',
      gameCode: 'hood-wolf',
      jackpot: true,
      newTab: true,
      provider: 'PGSoft',
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'pg_url'
    },
    {
      title: 'Hotpot',
      imgSrc: require('~imageAsset/lobby/game-center-item/pg-soft/hotpot.png'),
      loginRequired: true,
      gameId: '28',
      gameCode: 'hotpot',
      jackpot: true,
      newTab: true,
      provider: 'PGSoft',
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'pg_url'
    },
    {
      title: 'Dragon Legend',
      imgSrc: require('~imageAsset/lobby/game-center-item/pg-soft/dragon-legend.png'),
      loginRequired: true,
      gameId: '29',
      gameCode: 'dragon-legend',
      jackpot: true,
      newTab: true,
      provider: 'PGSoft',
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'pg_url'
    },
    {
      title: 'Mr. Hallow-Win',
      imgSrc: require('~imageAsset/lobby/game-center-item/pg-soft/mr-hallow-win.png'),
      loginRequired: true,
      gameId: '35',
      gameCode: 'mr-hallow-win',
      jackpot: true,
      newTab: true,
      provider: 'PGSoft',
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'pg_url'
    },
    {
      title: 'Legend of Hou Yi',
      imgSrc: require('~imageAsset/lobby/game-center-item/pg-soft/legend-of-hou-yi.png'),
      loginRequired: true,
      gameId: '34',
      gameCode: 'legend-of-hou-yi',
      jackpot: true,
      newTab: true,
      provider: 'PGSoft',
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'pg_url'
    },
    {
      title: 'Prosperity Lion',
      imgSrc: require('~imageAsset/lobby/game-center-item/pg-soft/prosperity-lion.png'),
      loginRequired: true,
      gameId: '36',
      gameCode: 'prosperity-lion',
      jackpot: true,
      newTab: true,
      provider: 'PGSoft',
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'pg_url'
    },
    {
      title: 'Hip Hop Panda',
      imgSrc: require('~imageAsset/lobby/game-center-item/pg-soft/hip-hop-panda.png'),
      loginRequired: true,
      gameId: '33',
      gameCode: 'hip-hop-panda',
      jackpot: true,
      newTab: true,
      provider: 'PGSoft',
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'pg_url'
    },
    {
      title: 'Santa\'s Gift Rush',
      imgSrc: require('~imageAsset/lobby/game-center-item/pg-soft/santa-gift-rush.png'),
      loginRequired: true,
      gameId: '37',
      gameCode: 'santas-gift-rush',
      jackpot: true,
      newTab: true,
      provider: 'PGSoft',
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'pg_url'
    },
    {
      title: 'Gem Saviour Sword',
      imgSrc: require('~imageAsset/lobby/game-center-item/pg-soft/gem-saviour-sword.png'),
      loginRequired: true,
      gameId: '38',
      gameCode: 'gem-saviour-sword',
      jackpot: true,
      newTab: true,
      provider: 'PGSoft',
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'pg_url'
    },
    {
      title: 'Piggy Gold',
      imgSrc: require('~imageAsset/lobby/game-center-item/pg-soft/piggy-gold.png'),
      loginRequired: true,
      gameId: '39',
      gameCode: 'piggy-gold',
      jackpot: true,
      newTab: true,
      provider: 'PGSoft',
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'pg_url'
    },
    {
      title: 'Symbols of Egypt',
      imgSrc: require('~imageAsset/lobby/game-center-item/pg-soft/symbols-of-egypt.png'),
      loginRequired: true,
      gameId: '41',
      gameCode: 'symbols-of-egypt',
      jackpot: true,
      newTab: true,
      provider: 'PGSoft',
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'pg_url'
    },
    {
      title: 'Emperor\'s Favour',
      imgSrc: require('~imageAsset/lobby/game-center-item/pg-soft/emperor-favour.png'),
      loginRequired: true,
      gameId: '44',
      gameCode: 'emperors-favour',
      jackpot: true,
      newTab: true,
      provider: 'PGSoft',
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'pg_url'
    },
    {
      title: 'Ganesha Gold',
      imgSrc: require('~imageAsset/lobby/game-center-item/pg-soft/ganesha-gold.png'),
      loginRequired: true,
      gameId: '42',
      gameCode: 'ganesha-gold',
      jackpot: true,
      newTab: true,
      provider: 'PGSoft',
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'pg_url'
    },
    {
      title: 'Three Monkeys',
      imgSrc: require('~imageAsset/lobby/game-center-item/pg-soft/three-monkeys.png'),
      loginRequired: true,
      gameId: '43',
      gameCode: 'three-monkeys',
      jackpot: true,
      newTab: true,
      provider: 'PGSoft',
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'pg_url'
    },
    {
      title: 'Jungle Delight',
      imgSrc: require('~imageAsset/lobby/game-center-item/pg-soft/jungle-delight.png'),
      loginRequired: true,
      gameId: '40',
      gameCode: 'jungle-delight',
      jackpot: true,
      newTab: true,
      provider: 'PGSoft',
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'pg_url'
    },
    {
      title: 'Double Fortune',
      imgSrc: require('~imageAsset/lobby/game-center-item/pg-soft/double-fortune.png'),
      loginRequired: true,
      gameId: '48',
      gameCode: 'double-fortune',
      jackpot: true,
      newTab: true,
      provider: 'PGSoft',
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'pg_url'
    },
    {
      title: 'The Great Icescape',
      imgSrc: require('~imageAsset/lobby/game-center-item/pg-soft/the-great-icescape.png'),
      loginRequired: true,
      gameId: '53',
      gameCode: 'the-great-icescape',
      jackpot: true,
      newTab: true,
      provider: 'PGSoft',
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'pg_url'
    },
    {
      title: 'Journey to the Wealth',
      imgSrc: require('~imageAsset/lobby/game-center-item/pg-soft/journey-to-the-wealth.png'),
      loginRequired: true,
      gameId: '50',
      gameCode: 'journey-to-the-wealth',
      jackpot: true,
      newTab: true,
      provider: 'PGSoft',
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'pg_url'
    },
    {
      title: 'Captain\'s Bounty',
      imgSrc: require('~imageAsset/lobby/game-center-item/pg-soft/captain-bounty.png'),
      loginRequired: true,
      gameId: '54',
      gameCode: 'captains-bounty',
      jackpot: true,
      newTab: true,
      provider: 'PGSoft',
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'pg_url'
    },
    {
      title: 'Leprechaun Riches',
      imgSrc: require('~imageAsset/lobby/game-center-item/pg-soft/leprechaun-riches.png'),
      loginRequired: true,
      gameId: '60',
      gameCode: 'leprechaun-riches',
      jackpot: true,
      newTab: true,
      provider: 'PGSoft',
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'pg_url'
    },
    {
      title: 'Flirting Scholar',
      imgSrc: require('~imageAsset/lobby/game-center-item/pg-soft/flirting-scholar.png'),
      loginRequired: true,
      gameId: '61',
      gameCode: 'flirting-scholar',
      jackpot: true,
      newTab: true,
      provider: 'PGSoft',
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'pg_url'
    },
    {
      title: 'Ninja vs Samurai',
      imgSrc: require('~imageAsset/lobby/game-center-item/pg-soft/ninja-vs-samurai.png'),
      loginRequired: true,
      gameId: '59',
      gameCode: 'ninja-vs-samurai',
      jackpot: true,
      newTab: true,
      provider: 'PGSoft',
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'pg_url'
    },
    {
      title: 'Muay Thai Champion',
      imgSrc: require('~imageAsset/lobby/game-center-item/pg-soft/muay-thai-champion.png'),
      loginRequired: true,
      gameId: '64',
      gameCode: 'muay-thai-champion',
      jackpot: true,
      newTab: true,
      provider: 'PGSoft',
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'pg_url'
    },
    {
      title: 'Dragon Tiger Luck',
      imgSrc: require('~imageAsset/lobby/game-center-item/pg-soft/dragon-tiger-luck.png'),
      loginRequired: true,
      gameId: '63',
      gameCode: 'dragon-tiger-luck',
      jackpot: true,
      newTab: true,
      provider: 'PGSoft',
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'pg_url'
    },
    {
      title: 'Mahjong Ways',
      imgSrc: require('~imageAsset/lobby/game-center-item/pg-soft/mahjong-ways.png'),
      loginRequired: true,
      gameId: '65',
      gameCode: 'mahjong-ways',
      jackpot: true,
      newTab: true,
      provider: 'PGSoft',
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'pg_url'
    },
    {
      title: 'Dragon Hatch',
      imgSrc: require('~imageAsset/lobby/game-center-item/pg-soft/dragon-hatch.png'),
      loginRequired: true,
      gameId: '57',
      gameCode: 'dragon-hatch',
      jackpot: true,
      newTab: true,
      provider: 'PGSoft',
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'pg_url'
    },
    {
      title: 'Fortune Mouse',
      imgSrc: require('~imageAsset/lobby/game-center-item/pg-soft/fortune-mouse.png'),
      loginRequired: true,
      gameId: '68',
      gameCode: 'fortune-mouse',
      jackpot: true,
      newTab: true,
      provider: 'PGSoft',
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'pg_url'
    },
    {
      title: 'Reel Love',
      imgSrc: require('~imageAsset/lobby/game-center-item/pg-soft/reel-love.png'),
      loginRequired: true,
      gameId: '20',
      gameCode: 'reel-love',
      jackpot: true,
      newTab: true,
      provider: 'PGSoft',
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'pg_url'
    },
    {
      title: 'Gem Saviour Conquest',
      imgSrc: require('~imageAsset/lobby/game-center-item/pg-soft/gem-saviour-conquest.png'),
      loginRequired: true,
      gameId: '62',
      gameCode: 'gem-saviour-conquest',
      jackpot: true,
      newTab: true,
      provider: 'PGSoft',
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'pg_url'
    },
    {
      title: 'Shaolin Soccer',
      imgSrc: require('~imageAsset/lobby/game-center-item/pg-soft/shaolin-soccer.png'),
      loginRequired: true,
      gameId: '67',
      gameCode: 'shaolin-soccer',
      jackpot: true,
      newTab: true,
      provider: 'PGSoft',
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'pg_url'
    },
    {
      title: 'Caishen Wins',
      imgSrc: require('~imageAsset/lobby/game-center-item/pg-soft/caishen-wins.png'),
      loginRequired: true,
      gameId: '71',
      gameCode: 'cai-shen-wins',
      jackpot: true,
      newTab: true,
      provider: 'PGSoft',
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'pg_url'
    },
    {
      title: 'Candy Burst',
      imgSrc: require('~imageAsset/lobby/game-center-item/pg-soft/candy-burst.png'),
      loginRequired: true,
      gameId: '70',
      gameCode: 'candy-burst',
      jackpot: true,
      newTab: true,
      provider: 'PGSoft',
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'pg_url'
    },
    {
      title: 'Bikini Paradise',
      imgSrc: require('~imageAsset/lobby/game-center-item/pg-soft/bikini-paradise.png'),
      loginRequired: true,
      gameId: '69',
      gameCode: 'bikini-paradise',
      jackpot: true,
      newTab: true,
      provider: 'PGSoft',
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'pg_url'
    },
    {
      title: 'Mahjong Ways 2',
      imgSrc: require('~imageAsset/lobby/game-center-item/pg-soft/mahjong-ways-2.png'),
      loginRequired: true,
      gameId: '74',
      gameCode: 'mahjong-ways2',
      jackpot: true,
      newTab: true,
      provider: 'PGSoft',
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'pg_url'
    },
    {
      title: 'Egypt\'s Book of Mystery',
      imgSrc: require('~imageAsset/lobby/game-center-item/pg-soft/egypt-book-of-mystery.png'),
      loginRequired: true,
      gameId: '73',
      gameCode: 'egypts-book-mystery',
      jackpot: true,
      newTab: true,
      provider: 'PGSoft',
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'pg_url'
    },
    {
      title: 'Ganesha Fortune',
      imgSrc: require('~imageAsset/lobby/game-center-item/pg-soft/ganesha-fortune.png'),
      loginRequired: true,
      gameId: '75',
      gameCode: 'ganesha-fortune',
      jackpot: true,
      newTab: true,
      provider: 'PGSoft',
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'pg_url'
    },
    {
      title: 'Phoenix Rises',
      imgSrc: require('~imageAsset/lobby/game-center-item/pg-soft/phoenix-rises.png'),
      loginRequired: true,
      gameId: '82',
      gameCode: 'phoenix-rises',
      jackpot: true,
      newTab: true,
      provider: 'PGSoft',
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'pg_url'
    },
    {
      title: 'Dreams of Macau',
      imgSrc: require('~imageAsset/lobby/game-center-item/pg-soft/dreams-of-macau.png'),
      loginRequired: true,
      gameId: '79',
      gameCode: 'dreams-of-macau',
      jackpot: true,
      newTab: true,
      provider: 'PGSoft',
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'pg_url'
    },
    {
      title: 'Wild Fireworks',
      imgSrc: require('~imageAsset/lobby/game-center-item/pg-soft/wild-fireworks.png'),
      loginRequired: true,
      gameId: '83',
      gameCode: 'wild-fireworks',
      jackpot: true,
      newTab: true,
      provider: 'PGSoft',
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'pg_url'
    },
    {
      title: 'Genie\'s 3 Wishes',
      imgSrc: require('~imageAsset/lobby/game-center-item/pg-soft/genie-3-wishes.png'),
      loginRequired: true,
      gameId: '85',
      gameCode: 'genies-wishes',
      jackpot: true,
      newTab: true,
      provider: 'PGSoft',
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'pg_url'
    },
    {
      title: 'Treasures of Aztec',
      imgSrc: require('~imageAsset/lobby/game-center-item/pg-soft/treasures-of-aztec.png'),
      loginRequired: true,
      gameId: '87',
      gameCode: 'treasures-aztec',
      jackpot: true,
      newTab: true,
      provider: 'PGSoft',
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'pg_url'
    },
    {
      title: 'Circus Delight',
      imgSrc: require('~imageAsset/lobby/game-center-item/pg-soft/circus-delight.png'),
      loginRequired: true,
      gameId: '80',
      gameCode: 'circus-delight',
      jackpot: true,
      newTab: true,
      provider: 'PGSoft',
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'pg_url'
    },
    {
      title: 'Thai River Wonders',
      imgSrc: require('~imageAsset/lobby/game-center-item/pg-soft/thai-river-wonders.png'),
      loginRequired: true,
      gameId: '92',
      gameCode: 'thai-river',
      jackpot: true,
      newTab: true,
      provider: 'PGSoft',
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'pg_url'
    },
    {
      title: 'Secret of Cleopatra',
      imgSrc: require('~imageAsset/lobby/game-center-item/pg-soft/secret-of-cleopatra.png'),
      loginRequired: true,
      gameId: '90',
      gameCode: 'sct-cleopatra',
      jackpot: true,
      newTab: true,
      provider: 'PGSoft',
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'pg_url'
    },
    {
      title: 'Vampire\'s Charm',
      imgSrc: require('~imageAsset/lobby/game-center-item/pg-soft/vampire-charm.png'),
      loginRequired: true,
      gameId: '58',
      gameCode: 'vampires-charm',
      jackpot: true,
      newTab: true,
      provider: 'PGSoft',
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'pg_url'
    },
    {
      title: 'Queen of Bounty',
      imgSrc: require('~imageAsset/lobby/game-center-item/pg-soft/queen-of-bounty.png'),
      loginRequired: true,
      gameId: '84',
      gameCode: 'queen-bounty',
      jackpot: true,
      newTab: true,
      provider: 'PGSoft',
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'pg_url'
    },
    {
      title: 'Jewels of Prosperity',
      imgSrc: require('~imageAsset/lobby/game-center-item/pg-soft/jewels-of-prosperity.png'),
      loginRequired: true,
      gameId: '88',
      gameCode: 'jewels-prosper',
      jackpot: true,
      newTab: true,
      provider: 'PGSoft',
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'pg_url'
    },
    {
      title: 'Lucky Neko',
      imgSrc: require('~imageAsset/lobby/game-center-item/pg-soft/lucky-neko.png'),
      loginRequired: true,
      gameId: '89',
      gameCode: 'lucky-neko',
      jackpot: true,
      newTab: true,
      provider: 'PGSoft',
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'pg_url'
    },
    {
      title: 'Jack Frost\'s Winter',
      imgSrc: require('~imageAsset/lobby/game-center-item/pg-soft/jack-frost-winter.png'),
      loginRequired: true,
      gameId: '97',
      gameCode: 'jack-frosts',
      jackpot: true,
      newTab: true,
      provider: 'PGSoft',
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'pg_url'
    },
    {
      title: 'Galactic Gems',
      imgSrc: require('~imageAsset/lobby/game-center-item/pg-soft/galactic-gems.png'),
      loginRequired: true,
      gameId: '86',
      gameCode: 'galactic-gems',
      jackpot: true,
      newTab: true,
      provider: 'PGSoft',
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'pg_url'
    },
    {
      title: 'Guardians of Ice and Fire',
      imgSrc: require('~imageAsset/lobby/game-center-item/pg-soft/guardians-of-ice-and-fire.png'),
      loginRequired: true,
      gameId: '91',
      gameCode: 'gdn-ice-fire',
      jackpot: true,
      newTab: true,
      provider: 'PGSoft',
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'pg_url'
    },
    {
      title: 'Opera Dynasty',
      imgSrc: require('~imageAsset/lobby/game-center-item/pg-soft/opera-dynasty.png'),
      loginRequired: true,
      gameId: '93',
      gameCode: 'opera-dynasty',
      jackpot: true,
      newTab: true,
      provider: 'PGSoft',
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'pg_url'
    },
    {
      title: 'Fortune Ox',
      imgSrc: require('~imageAsset/lobby/game-center-item/pg-soft/fortune-ox.png'),
      loginRequired: true,
      gameId: '98',
      gameCode: 'fortune-ox',
      jackpot: true,
      newTab: true,
      provider: 'PGSoft',
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'pg_url'
    },
    {
      title: 'Bali Vacation',
      imgSrc: require('~imageAsset/lobby/game-center-item/pg-soft/bali-vacation.png'),
      loginRequired: true,
      gameId: '94',
      gameCode: 'bali-vacation',
      jackpot: true,
      newTab: true,
      provider: 'PGSoft',
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'pg_url'
    },
    {
      title: 'Crypto Gold',
      imgSrc: require('~imageAsset/lobby/game-center-item/pg-soft/crypto-gold.png'),
      loginRequired: true,
      gameId: '103',
      gameCode: 'crypto-gold',
      jackpot: true,
      newTab: true,
      provider: 'PGSoft',
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'pg_url'
    },
    {
      title: 'Majestic Treasures',
      imgSrc: require('~imageAsset/lobby/game-center-item/pg-soft/majestic-treasures.png'),
      loginRequired: true,
      gameId: '95',
      gameCode: 'majestic-ts',
      jackpot: true,
      newTab: true,
      provider: 'PGSoft',
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'pg_url'
    },
    {
      title: 'Candy Bonanza',
      imgSrc: require('~imageAsset/lobby/game-center-item/pg-soft/candy-bonanza.png'),
      loginRequired: true,
      gameId: '100',
      gameCode: 'candy-bonanza',
      jackpot: true,
      newTab: true,
      provider: 'PGSoft',
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'pg_url'
    },
    {
      title: 'Ways of the Qilin',
      imgSrc: require('~imageAsset/lobby/game-center-item/pg-soft/ways-of-the-qilin.png'),
      loginRequired: true,
      gameId: '106',
      gameCode: 'ways-of-qilin',
      jackpot: true,
      newTab: true,
      provider: 'PGSoft',
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'pg_url'
    },
    {
      title: 'Wild Bandito',
      imgSrc: require('~imageAsset/lobby/game-center-item/pg-soft/wild-bandito.png'),
      loginRequired: true,
      gameId: '104',
      gameCode: 'wild-bandito',
      jackpot: true,
      newTab: true,
      provider: 'PGSoft',
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'pg_url'
    },
    {
      title: 'Candy',
      imgSrc: require('~imageAsset/lobby/game-center-item/slot/candy.png'),
      loginRequired: true,
      gameId: 'vgmn_202',
      newTab: true,
      provider: 'PGSoft',
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'gamebai_url'
    },
    {
      title: 'Vòng Quay May Mắn',
      imgSrc: require('~imageAsset/lobby/game-center-item/slot/vong-quay-may-man.png'),
      loginRequired: true,
      gameId: 'vgs_219',
      newTab: true,
      provider: 'PGSoft',
      promotionPrevent: true,
      wallet: WALLET.SUB,
      gameType: 'gamebai_url'
    },
    {
      title: 'Slot Night Club',
      imgSrc: require('~imageAsset/lobby/game-center-item/slot/slot-night-club.png'),
      loginRequired: true,
      gameId: 'vgs_218',
      newTab: true,
      provider: 'PGSoft',
      promotionPrevent: true,
      wallet: WALLET.SUB,
      gameType: 'gamebai_url'
    }
  ],
  jackpots: [
    {
      title: 'Long Quy Chi Bảo',
      imgSrc: require('~imageAsset/lobby/game-center-item/slot/long-quy-chi-bao.png'),
      loginRequired: true,
      gameId: 'kts9980',
      jackpot: true,
      provider: 'Techplay',
      newTab: true,
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'gp_url'
    },
    {
      title: 'Biệt Đội Mỹ Nữ',
      imgSrc: require('~imageAsset/lobby/game-center-item/slot/biet-doi-my-nu.png'),
      loginRequired: true,
      gameId: 'kts9996',
      jackpot: true,
      provider: 'Techplay',
      newTab: true,
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'gp_url'
    },
    {
      title: 'Ma Đao Lệ Ảnh',
      imgSrc: require('~imageAsset/lobby/game-center-item/slot/ma-dao-le-anh.png'),
      loginRequired: true,
      gameId: 'kts9984',
      jackpot: true,
      provider: 'Techplay',
      newTab: true,
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'gp_url'
    },
    {
      title: 'The Witcher',
      imgSrc: require('~imageAsset/lobby/game-center-item/slot/the-witcher.png'),
      loginRequired: true,
      gameId: 'kts9985',
      jackpot: true,
      provider: 'Techplay',
      newTab: true,
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'gp_url'
    },
    {
      title: 'Tứ Linh Thần Thú',
      imgSrc: require('~imageAsset/lobby/game-center-item/slot/tu-linh-than-thu.png'),
      loginRequired: true,
      gameId: 'kts9991',
      jackpot: true,
      provider: 'Techplay',
      newTab: true,
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'gp_url'
    },
    {
      title: 'Đường Tới Qatar',
      imgSrc: require('~imageAsset/lobby/game-center-item/slot/duong-den-qatar.png'),
      loginRequired: true,
      gameId: 'kts9982',
      jackpot: true,
      provider: 'Techplay',
      newTab: true,
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'gp_url'
    },
    {
      title: 'Thần Lực Bóng Tối',
      imgSrc: require('~imageAsset/lobby/game-center-item/slot/than-luc-bong-toi.png'),
      loginRequired: true,
      gameId: 'kts9989',
      jackpot: true,
      provider: 'Techplay',
      newTab: true,
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'gp_url'
    },
    {
      title: 'Aladdin',
      imgSrc: require('~imageAsset/lobby/game-center-item/slot/aladin.png'),
      loginRequired: true,
      gameId: 'kts9976',
      jackpot: true,
      provider: 'Techplay',
      newTab: true,
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'gp_url'
    },
    {
      title: 'Thanh Xà Bạch Xà',
      imgSrc: require('~imageAsset/lobby/game-center-item/slot/thanh-xa-bach-xa.jpg'),
      loginRequired: true,
      gameId: 'kts9994',
      jackpot: true,
      provider: 'Techplay',
      newTab: true,
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'gp_url'
    },
    {
      title: 'Thằng Bờm',
      imgSrc: require('~imageAsset/lobby/game-center-item/slot/thang-bom.jpg'),
      loginRequired: true,
      gameId: 'kts9997',
      jackpot: true,
      provider: 'Techplay',
      newTab: true,
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'gp_url'
    },
    {
      title: 'Tam Quốc Tranh Hùng',
      imgSrc: require('~imageAsset/lobby/game-center-item/slot/tam-quoc-tranh-hung.png'),
      loginRequired: true,
      gameId: 'kts9992',
      jackpot: true,
      provider: 'Techplay',
      newTab: true,
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'gp_url'
    },
    {
      title: 'Sơn Tinh Thủy Tinh',
      imgSrc: require('~imageAsset/lobby/game-center-item/slot/son-tinh-thuy-tinh.png'),
      loginRequired: true,
      gameId: 'kts9999',
      jackpot: true,
      provider: 'Techplay',
      newTab: true,
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'gp_url'
    },
    {
      title: 'Metal Gear Solid',
      imgSrc: require('~imageAsset/lobby/game-center-item/slot/metal-gear-solid.png'),
      loginRequired: true,
      gameId: 'kts9977',
      jackpot: true,
      provider: 'Techplay',
      newTab: true,
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'gp_url'
    },
    {
      title: 'Bí Mật Cleopatra',
      imgSrc: require('~imageAsset/lobby/game-center-item/slot/cleopatra.png'),
      loginRequired: true,
      gameId: 'kts9988',
      jackpot: true,
      provider: 'Techplay',
      newTab: true,
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'gp_url'
    },
    {
      title: 'Call Of War',
      imgSrc: require('~imageAsset/lobby/game-center-item/slot/call-of-war.png'),
      loginRequired: true,
      gameId: 'kts9979',
      jackpot: true,
      provider: 'Techplay',
      newTab: true,
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'gp_url'
    },
    {
      title: 'Bắn Cá Hoàng Gia',
      imgSrc: require('~imageAsset/lobby/game-center-item/fishing/ban-ca-hoang-gia.png'),
      loginRequired: true,
      gameId: 'ktf_1999',
      jackpot: true,
      provider: 'Techplay',
      newTab: true,
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'gp_url'
    },
    {
      title: 'Không lực hoàng gia',
      imgSrc: require('~imageAsset/lobby/game-center-item/fishing/khong-luc-hoang-gia.png'),
      loginRequired: true,
      gameId: 'ktf_1997',
      jackpot: true,
      provider: 'Techplay',
      newTab: true,
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'gp_url',
      feature: true,
      order: 2
    }
  ],
  fishing: [
    {
      title: 'Vua Bắn Cá',
      imgSrc: require('~imageAsset/lobby/game-center-item/fishing/vua-ban-ca.jpg'),
      loginRequired: true,
      gameId: 'ktf1998',
      jackpot: true,
      provider: 'Techplay',
      newTab: true,
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'gp_url'
    },
    {
      title: 'Bắn Cá Hoàng Gia',
      imgSrc: require('~imageAsset/lobby/game-center-item/fishing/ban-ca-hoang-gia.png'),
      loginRequired: true,
      gameId: 'ktf_1999',
      jackpot: true,
      provider: 'Techplay',
      newTab: true,
      promotionPrevent: false,
      wallet: WALLET.SUB,
      feature: true,
      gameType: 'gp_url',
      order: 1
    },
    {
      title: 'Bắn Cá Vui Nhộn',
      imgSrc: require('~imageAsset/lobby/game-center-item/fishing/ban-ca-vui-nhon.png'),
      loginRequired: true,
      apiUrl: '/games/cq9Url',
      gameId: 'AT05',
      provider: 'CQ9',
      newTab: true,
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: ''
    },
    {
      title: 'Bắn Cá Tâm Tiễn',
      imgSrc: require('~imageAsset/lobby/game-center-item/fishing/ban-ca-tam-tien.png'),
      loginRequired: true,
      apiUrl: '/games/cq9Url',
      gameId: 'AT01',
      provider: 'CQ9',
      newTab: true,
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: ''
    },
    {
      title: 'Bắn Cá Thủy Hử',
      imgSrc: require('~imageAsset/lobby/game-center-item/fishing/ban-ca-thuy-hu.png'),
      loginRequired: true,
      apiUrl: '/games/cq9Url',
      gameId: 'AT06',
      provider: 'CQ9',
      newTab: true,
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: ''
    },
    {
      title: 'Thiên Đường Săn Cá',
      imgSrc: require('~imageAsset/lobby/game-center-item/fishing/thien-duong-san-ca.png'),
      loginRequired: true,
      apiUrl: '/games/cq9Url',
      gameId: 'AB3',
      provider: 'CQ9',
      newTab: true,
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: ''
    },
    {
      title: 'Không lực hoàng gia',
      imgSrc: require('~imageAsset/lobby/game-center-item/fishing/khong-luc-hoang-gia.png'),
      loginRequired: true,
      gameId: 'ktf_1997',
      jackpot: true,
      provider: 'Techplay',
      newTab: true,
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'gp_url'
    }
  ],
  ingame: [
    {
      title: 'Sicbo Deadpool',
      imgSrc: require('~imageAsset/lobby/game-center-item/ingame/sicbo-deadpool.jpg'),
      loginRequired: true,
      gameId: 'ktrng3986',
      provider: 'Techplay',
      newTab: true,
      promotionPrevent: true,
      wallet: WALLET.SUB,
      gameType: 'gp_url'
    },
    {
      title: 'Xèng Tài Xỉu',
      imgSrc: require('~imageAsset/lobby/game-center-item/ingame/xeng.jpg'),
      loginRequired: true,
      gameId: 'ktrng3985',
      provider: 'Techplay',
      newTab: true,
      promotionPrevent: true,
      wallet: WALLET.SUB,
      gameType: 'gp_url'
    },
    {
      title: 'Baccarat Super 6',
      imgSrc: require('~imageAsset/lobby/game-center-item/ingame/baccarat-super-6.png'),
      loginRequired: true,
      gameId: 'ktrng_3992',
      provider: 'Techplay',
      newTab: true,
      promotionPrevent: true,
      wallet: WALLET.SUB,
      gameType: 'gp_url'
    },
    {
      title: 'Long Lân Quy Phụng',
      imgSrc: require('~imageAsset/lobby/game-center-item/ingame/long-lan-quy-phung.png'),
      loginRequired: true,
      gameId: 'ktrng_3999',
      provider: 'Techplay',
      newTab: true,
      promotionPrevent: true,
      wallet: WALLET.SUB,
      gameType: 'gp_url'
    },
    {
      title: 'Sicbo Sảnh Rồng',
      imgSrc: require('~imageAsset/lobby/game-center-item/ingame/tai-xiu-song-long.png'),
      loginRequired: true,
      gameId: 'ktrng_3998',
      provider: 'Techplay',
      newTab: true,
      promotionPrevent: true,
      wallet: WALLET.SUB,
      gameType: 'gp_url',
      feature: true,
      order: 7
    },
    {
      title: 'Baccarat Classic',
      imgSrc: require('~imageAsset/lobby/game-center-item/ingame/baccarat-classic.png'),
      loginRequired: true,
      gameId: 'ktrng_3997',
      provider: 'Techplay',
      newTab: true,
      promotionPrevent: true,
      wallet: WALLET.SUB,
      gameType: 'gp_url'
    },
    {
      title: 'Bull Bull',
      imgSrc: require('~imageAsset/lobby/game-center-item/ingame/bull-bull.png'),
      loginRequired: true,
      gameId: 'ktrng_3991',
      jackpot: true,
      provider: 'Techplay',
      newTab: true,
      promotionPrevent: true,
      wallet: WALLET.SUB,
      gameType: 'gp_url'
    },
    {
      title: 'Roulette',
      imgSrc: require('~imageAsset/lobby/game-center-item/ingame/roulette.png'),
      loginRequired: true,
      gameId: 'ktrng_3994',
      jackpot: true,
      provider: 'Techplay',
      newTab: true,
      promotionPrevent: true,
      wallet: WALLET.SUB,
      gameType: 'gp_url'
    },
    {
      title: 'Dragon Tiger',
      imgSrc: require('~imageAsset/lobby/game-center-item/ingame/dragon-tiger.png'),
      loginRequired: true,
      gameId: 'ktrng_3989',
      jackpot: true,
      provider: 'Techplay',
      newTab: true,
      promotionPrevent: true,
      wallet: WALLET.SUB,
      gameType: 'gp_url'
    },
    {
      title: 'Caribbean stud poker',
      imgSrc: require('~imageAsset/lobby/game-center-item/ingame/caribbean-stub-poker.png'),
      loginRequired: true,
      gameId: 'ktrng_3988',
      provider: 'vingame',
      newTab: true,
      promotionPrevent: true,
      wallet: WALLET.SUB,
      gameType: 'gp_url'
    }
  ],
  lottery: [
    {
      title: 'Quay Số CyberPunk',
      imgSrc: require('~imageAsset/lobby/game-center-item/lottery/quayso-cyber.png'),
      loginRequired: true,
      gameUrl: LOTTERY_CYBER_PUNK,
      provider: '',
      newTab: false,
      promotionPrevent: true,
      wallet: WALLET.SUB,
      feature: true,
      gameType: '',
      order: 5
    },
    {
      title: 'Quay Số Las Vegas',
      imgSrc: require('~imageAsset/lobby/game-center-item/lottery/quayso-las-vegas.png'),
      loginRequired: true,
      gameUrl: LOTTERY_LAS_VEGAS,
      provider: '',
      newTab: false,
      promotionPrevent: true,
      wallet: WALLET.SUB,
      gameType: ''
    }
  ],
  instant_games: [
    {
      title: 'Aviator',
      imgSrc: require('~imageAsset/lobby/game-center-item/spribe/aviator.png'),
      loginRequired: true,
      gameId: 'aviator',
      provider: 'Spribe Games',
      newTab: true,
      promotionPrevent: false,
      wallet: WALLET.SUB,
      feature: true,
      gameType: 'instant_games_url',
      order: 11
    },
    {
      title: 'Dice',
      imgSrc: require('~imageAsset/lobby/game-center-item/spribe/dice.png'),
      loginRequired: true,
      gameId: 'dice',
      provider: 'Spribe Games',
      newTab: true,
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'instant_games_url'
    },
    {
      title: 'Goal',
      imgSrc: require('~imageAsset/lobby/game-center-item/spribe/goal.png'),
      loginRequired: true,
      gameId: 'goal',
      provider: 'Spribe Games',
      newTab: true,
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'instant_games_url'
    },
    {
      title: 'Hilo',
      imgSrc: require('~imageAsset/lobby/game-center-item/spribe/hilo.png'),
      loginRequired: true,
      gameId: 'hi-lo',
      provider: 'Spribe Games',
      newTab: true,
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'instant_games_url'
    },
    {
      title: 'Keno',
      imgSrc: require('~imageAsset/lobby/game-center-item/spribe/spribe_keno.png'),
      loginRequired: true,
      gameId: 'keno',
      provider: 'Spribe Games',
      newTab: true,
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'instant_games_url'
    },
    {
      title: 'Mine',
      imgSrc: require('~imageAsset/lobby/game-center-item/spribe/mine.png'),
      loginRequired: true,
      gameId: 'mines',
      provider: 'Spribe Games',
      newTab: true,
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'instant_games_url'
    },
    {
      title: 'Mini Roulette',
      imgSrc: require('~imageAsset/lobby/game-center-item/spribe/mini_roulette.png'),
      loginRequired: true,
      gameId: 'mini-roulette',
      provider: 'Spribe Games',
      newTab: true,
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'instant_games_url'
    },
    {
      title: 'Plinko',
      imgSrc: require('~imageAsset/lobby/game-center-item/spribe/plinko.png'),
      loginRequired: true,
      gameId: 'plinko',
      provider: 'Spribe Games',
      newTab: true,
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'instant_games_url'
    }
  ],
  quickgame: [
    {
      title: 'Keno',
      imgSrc: require('~imageAsset/lobby/game-center-item/quickgame/keno.png'),
      loginRequired: true,
      gameUrl: '/keno',
      provider: '',
      newTab: false,
      promotionPrevent: false,
      wallet: WALLET.MAIN,
      feature: true,
      gameType: 'keno_url',
      order: 4
    },
    {
      title: 'Lottery',
      imgSrc: require('~imageAsset/lobby/game-center-item/quickgame/lottery.png'),
      loginRequired: true,
      gameUrl: '/lottery',
      provider: '',
      newTab: false,
      promotionPrevent: false,
      wallet: WALLET.MAIN,
      feature: true,
      order: 9
    },
    {
      title: 'Numbers Game',
      imgSrc: require('~imageAsset/lobby/game-center-item/quickgame/numbersgame.png'),
      loginRequired: false,
      gameUrl: '/numbergame',
      provider: '',
      newTab: false,
      promotionPrevent: false,
      wallet: WALLET.MAIN,
      feature: true,
      order: 6
    },
    {
      title: 'Saba Games',
      imgSrc: require('~imageAsset/lobby/game-center-item/quickgame/saba.png'),
      loginRequired: true,
      gameUrl: '/saba-club',
      provider: '',
      newTab: false,
      promotionPrevent: false,
      wallet: WALLET.MAIN
    },
    {
      title: 'Table Games',
      imgSrc: require('~imageAsset/lobby/game-center-item/quickgame/tablegame.png'),
      loginRequired: true,
      gameUrl: '/tablegame',
      provider: '',
      newTab: false,
      promotionPrevent: false,
      wallet: WALLET.MAIN,
      feature: true,
      order: 8
    },
    {
      title: 'Virtual Games',
      imgSrc: require('~imageAsset/lobby/game-center-item/quickgame/virtualgame.png'),
      loginRequired: true,
      gameUrl: '/virtualgame',
      provider: '',
      newTab: false,
      promotionPrevent: false,
      wallet: WALLET.MAIN,
      feature: true,
      order: 10
    },
    {
      title: 'Keno TP',
      imgSrc: require('~imageAsset/lobby/game-center-item/quickgame/keno-tp.png'),
      loginRequired: true,
      gameUrl: '/tp-keno',
      provider: '',
      newTab: false,
      promotionPrevent: false,
      wallet: WALLET.SUB
    },
    {
      title: 'Numbers Game TP',
      imgSrc: require('~imageAsset/lobby/game-center-item/quickgame/numbersgametp.png'),
      loginRequired: true,
      gameUrl: '/tp-numbergame',
      provider: '',
      newTab: false,
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'tp_number_game_url'
    }
  ],
  lode: [
    {
      title: 'Lô Đề 3 miền',
      imgSrc: require('~imageAsset/lobby/game-center-item/lode/lode3mien.png'),
      loginRequired: true,
      newTab: false,
      provider: 'Lo De',
      promotionPrevent: false,
      gameUrl: LODE,
      wallet: WALLET.SUB,
      feature: true,
      gameType: '',
      order: 3
    },
    {
      title: 'Lô Đề Siêu Tốc',
      imgSrc: require('~imageAsset/lobby/game-center-item/lode/lo-de-sieu-toc.png'),
      loginRequired: true,
      newTab: false,
      provider: 'Lo De',
      promotionPrevent: false,
      gameUrl: LODE_SIEUTOC,
      wallet: WALLET.SUB,
      gameType: ''
    }
  ],
  battle_games: [
    {
      title: 'Cờ Úp',
      imgSrc: require('~imageAsset/lobby/game-center-item/battle/coup.jpg'),
      loginRequired: true,
      gameId: 'ktc7993',
      jackpot: true,
      provider: 'Techplay',
      newTab: true,
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'gp_url'
    }
  ],
  table_games: [
    {
      title: 'European Blackjack',
      imgSrc: require('~imageAsset/lobby/game-center-item/pg-soft/european-blackjack.png'),
      loginRequired: true,
      gameId: '12',
      gameCode: 'blackjack-eu',
      jackpot: true,
      newTab: true,
      provider: 'PGSoft',
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'pg_url'
    },
    {
      title: 'American Blackjack',
      imgSrc: require('~imageAsset/lobby/game-center-item/pg-soft/american-blackjack.png'),
      loginRequired: true,
      gameId: '11',
      gameCode: 'blackjack-us',
      jackpot: true,
      newTab: true,
      provider: 'PGSoft',
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'pg_url'
    },
    {
      title: 'Baccarat Deluxe',
      imgSrc: require('~imageAsset/lobby/game-center-item/pg-soft/baccarat-deluxe.png'),
      loginRequired: true,
      gameId: '31',
      gameCode: 'baccarat-deluxe',
      jackpot: true,
      newTab: true,
      provider: 'PGSoft',
      promotionPrevent: false,
      wallet: WALLET.SUB,
      gameType: 'pg_url'
    },
    {
      title: 'Saba Games',
      imgSrc: require('~imageAsset/lobby/game-center-item/quickgame/saba.png'),
      loginRequired: true,
      gameUrl: '/saba-club',
      provider: '',
      newTab: false,
      promotionPrevent: false,
      wallet: WALLET.MAIN
    }
  ],
  gamebai: [
    {
      title: 'Bầu Cua',
      imgSrc: require('~imageAsset/lobby/game-center-item/gamebai/bau-cua.png'),
      loginRequired: true,
      gameId: 'vgcg_14',
      newTab: true,
      promotionPrevent: true,
      wallet: WALLET.SUB,
      gameType: 'gamebai_url'
    },
    {
      title: 'Poker OHama',
      imgSrc: require('~imageAsset/lobby/game-center-item/gamebai/poker-ohama.png'),
      loginRequired: true,
      gameId: 'vgcg_12',
      newTab: true,
      promotionPrevent: true,
      wallet: WALLET.SUB,
      gameType: 'gamebai_url'
    },
    {
      title: 'POKER',
      imgSrc: require('~imageAsset/lobby/game-center-item/gamebai/pocker.png'),
      loginRequired: true,
      gameId: 'vgcg_6',
      newTab: true,
      promotionPrevent: true,
      wallet: WALLET.SUB,
      gameType: 'gamebai_url'
    },
    {
      title: 'Phỏm',
      imgSrc: require('~imageAsset/lobby/game-center-item/gamebai/phom.png'),
      loginRequired: true,
      gameId: 'vgcg_8',
      newTab: true,
      promotionPrevent: true,
      wallet: WALLET.SUB,
      gameType: 'gamebai_url'
    },
    {
      title: 'Binh',
      imgSrc: require('~imageAsset/lobby/game-center-item/gamebai/binh.png'),
      loginRequired: true,
      gameId: 'vgcg_4',
      newTab: true,
      promotionPrevent: true,
      wallet: WALLET.SUB,
      gameType: 'gamebai_url'
    },
    {
      title: 'Tài Xỉu',
      imgSrc: require('~imageAsset/lobby/game-center-item/gamebai/tai-xiu.png'),
      loginRequired: true,
      gameId: 'vgmn_100',
      newTab: true,
      promotionPrevent: true,
      wallet: WALLET.SUB,
      gameType: 'gamebai_url'
    },
    {
      title: 'Poker Tournament',
      imgSrc: require('~imageAsset/lobby/game-center-item/gamebai/poker-tournament.png'),
      loginRequired: true,
      gameId: 'vgcg_17',
      newTab: true,
      promotionPrevent: true,
      wallet: WALLET.SUB,
      gameType: 'gamebai_url'
    },
    {
      title: 'Tiến Lên',
      imgSrc: require('~imageAsset/lobby/game-center-item/gamebai/tien-len.png'),
      loginRequired: true,
      gameId: 'vgcg_1',
      newTab: true,
      promotionPrevent: true,
      wallet: WALLET.SUB,
      gameType: 'gamebai_url'
    },
    {
      title: 'Xóc Đĩa',
      imgSrc: require('~imageAsset/lobby/game-center-item/gamebai/xoc-dia.png'),
      loginRequired: true,
      gameId: 'vgcg_9',
      newTab: true,
      promotionPrevent: true,
      wallet: WALLET.SUB,
      gameType: 'gamebai_url'
    },
    {
      title: 'Bầu Cua Mini',
      imgSrc: require('~imageAsset/lobby/game-center-item/gamebai/bau-cua-mini.png'),
      loginRequired: true,
      gameId: 'bcmini',
      newTab: true,
      promotionPrevent: true,
      wallet: WALLET.SUB,
      gameType: 'gamebai_url'
    },
    {
      title: 'Mini Poker',
      imgSrc: require('~imageAsset/lobby/game-center-item/gamebai/mini-pocker.png'),
      loginRequired: true,
      gameId: 'vgmn_201',
      newTab: true,
      promotionPrevent: true,
      wallet: WALLET.SUB,
      gameType: 'gamebai_url'
    }
  ]
}

Object.keys(lobbyGame).forEach((index) => {
  const value = lobbyGame[index].filter(function (game) {
    return game.feature === true
  })
  lobbyGame.hotgame.push(...value)

  // Make Hot Game List show with correct order
  lobbyGame.hotgame.sort((pre, nxt) => pre.order - nxt.order)
})

export { lobbyGame }
