import { WALLET } from '@/config/constant'

const lobbyCasino = {
  hotgame: [],
  baccarat: [
    {
      title: 'Speed Baccarat A',
      category: 'baccarat',
      tableId: 'leqhceumaq6qfoug',
      gameId: 'lcevo_1006baccarat',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/baccarats/speed-baccarat-a.png'),
      range: '20 Đ - 100.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB,
      feature: true
    },
    {
      title: 'Speed Baccarat B',
      category: 'baccarat',
      tableId: 'lv2kzclunt2qnxo5',
      gameId: 'lcevo_1006lightningdice',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/baccarats/speed-baccarat-b.png'),
      range: '20 Đ - 100.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB
    },
    {
      title: 'Speed Baccarat C',
      category: 'baccarat',
      tableId: 'ndgvwvgthfuaad3q',
      gameId: 'lcevo_1006baccarat',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/baccarats/speed-baccarat-c.png'),
      range: '20 Đ - 100.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB
    },
    {
      title: 'Speed Baccarat D',
      category: 'baccarat',
      tableId: 'ndgvz5mlhfuaad6e',
      gameId: 'lcevo_1006baccarat',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/baccarats/speed-baccarat-d.png'),
      range: '20.000 Đ - 100.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB
    },
    {
      title: 'Speed Baccarat E',
      category: 'baccarat',
      tableId: 'ndgv45bghfuaaebf',
      gameId: 'lcevo_1006baccarat',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/baccarats/speed-baccarat-e.png'),
      range: '20 Đ - 100.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB
    },
    {
      title: 'Speed Baccarat F',
      category: 'baccarat',
      tableId: 'nmwde3fd7hvqhq43',
      gameId: 'lcevo_1006baccarat',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/baccarats/speed-baccarat-f.png'),
      range: '20 Đ - 100.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB
    },
    {
      title: 'Speed Baccarat G',
      category: 'baccarat',
      tableId: 'nmwdzhbg7hvqh6a7',
      gameId: 'lcevo_1006baccarat',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/baccarats/speed-baccarat-g.png'),
      range: '20 Đ - 100.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB
    },
    {
      title: 'Speed Baccarat H',
      category: 'baccarat',
      tableId: 'nxpj4wumgclak2lx',
      gameId: 'lcevo_1006blackjack',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/baccarats/speed-baccarat-h.png'),
      range: '20 Đ - 100.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB
    },
    {
      title: 'Speed Baccarat I',
      category: 'baccarat',
      tableId: 'nxpkul2hgclallno',
      gameId: 'lcevo_1006trp',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/baccarats/speed-baccarat-i.png'),
      range: '20 Đ - 100.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB
    },
    {
      title: 'Speed Baccarat J',
      category: 'baccarat',
      tableId: 'obj64qcnqfunjelj',
      gameId: 'lcevo_1006baccarat',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/baccarats/speed-baccarat-l.png'),
      range: '20 Đ - 100.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB
    },
    {
      title: 'Speed Baccarat L',
      category: 'baccarat',
      tableId: 'ovu5cwp54ccmymck',
      gameId: 'lcevo_1006blackjack',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/baccarats/speed-baccarat-l.png'),
      range: '20 Đ - 100.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB
    },
    {
      title: 'Speed Baccarat M',
      category: 'baccarat',
      tableId: 'ovu5dsly4ccmynil',
      gameId: 'lcevo_1006baccarat',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/baccarats/speed-baccarat-m.png'),
      range: '20 Đ - 100.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB
    },
    {
      title: 'Speed Baccarat N',
      category: 'baccarat',
      tableId: 'ovu5eja74ccmyoiq',
      gameId: 'lcevo_1006baccarat',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/baccarats/speed-baccarat-n.png'),
      range: '20.000 Đ - 100.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB
    },
    {
      title: 'Speed Baccarat O',
      category: 'baccarat',
      tableId: 'ovu5fbxm4ccmypmb',
      gameId: 'lcevo_1006baccarat',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/baccarats/speed-baccarat-o.png'),
      range: '20 Đ - 100.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB
    },
    {
      title: 'No Commission Speed Baccarat A',
      category: 'baccarat',
      tableId: 'ndgv76kehfuaaeec',
      gameId: 'lcevo_1006trp',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/baccarats/no-commision-speed-baccarat-a.png'),
      range: '20 Đ - 100.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB,
      feature: true
    },
    {
      title: 'No Commission Baccarat',
      category: 'baccarat',
      tableId: 'NoCommBac0000001',
      gameId: 'lcevo_1006baccarat',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/baccarats/no-commision-baccarat.png'),
      range: '20 Đ - 100.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB
    },
    {
      title: 'Baccarat A',
      category: 'baccarat',
      tableId: 'oytmvb9m1zysmc44',
      gameId: 'lcevo_1006baccarat',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/baccarats/baccarat-a.png'),
      range: '20 Đ - 100.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB
    },
    {
      title: 'Baccarat B',
      category: 'baccarat',
      tableId: '60i0lcfx5wkkv3sy',
      gameId: 'lcevo_1006baccarat',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/baccarats/baccarat-b.png'),
      range: '20 Đ - 100.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB
    },
    {
      title: 'Baccarat C',
      category: 'baccarat',
      tableId: 'ndgvs3tqhfuaadyg',
      gameId: 'lcevo_1006baccarat',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/baccarats/baccarat-c.png'),
      range: '20 Đ - 100.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB
    },
    {
      title: 'Baccarat Squeeze',
      category: 'baccarat',
      tableId: 'zixzea8nrf1675oh',
      gameId: 'lcevo_1006baccarat',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/baccarats/baccarat-squeeze.png'),
      range: '20 Đ - 100.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB
    },
    {
      title: 'Baccarat Control Squeeze',
      category: 'baccarat',
      tableId: 'k2oswnib7jjaaznw',
      gameId: 'lcevo_1006baccarat',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/baccarats/baccarat-control-squeeze.png'),
      range: '20 Đ - 100.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB
    },
    {
      title: 'Salon Prive Baccarat A',
      category: 'baccarat',
      tableId: 'SalPrivBac000001',
      gameId: 'cevo_1006baccarat',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/baccarats/salon-prive-baccarat-a.png'),
      range: '20.000 Đ - 300.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB
    },
    {
      title: 'Salon Prive Baccarat B',
      category: 'baccarat',
      tableId: 'n7ltqx5j25sr7xbe',
      gameId: 'cevo_1006baccarat',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/baccarats/salon-prive-baccarat-b.png'),
      range: '20.000 Đ - 300.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB
    },
    {
      title: 'Salon Prive Baccarat C',
      category: 'baccarat',
      tableId: 'ok37hvy3g7bofp4l',
      gameId: 'cevo_1006baccarat',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/baccarats/baccarat-c.png'),
      range: '20.000 Đ - 300.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB
    }
  ],
  tablegame: [
    {
      title: 'First Person Baccarat',
      category: 'rng-baccarat',
      tableId: 'rngbaccarat00000',
      gameId: 'lcevo_1006rng-baccarat',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/tablegames/first-person-baccarat.png'),
      range: '20 Đ - 100.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB
    },
    {
      title: 'First Person Blackjack',
      category: 'rngblackjack',
      tableId: 'rng-bj-standard0',
      gameId: 'lcevo_1006dealnodeal',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/tablegames/first-person-blackjack.png'),
      range: '10 Đ - 20.000 Đ',
      loginRequired: true,
      newTab: false,
      wallet: WALLET.SUB
    },
    {
      title: 'First Person Dragon Tiger',
      category: 'rng-dragontiger',
      tableId: 'rng-dragontiger0',
      gameId: 'lcevo_1006rng-dragontiger',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/tablegames/first-person-dragon-tiger.png'),
      range: '20 Đ - 100.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB
    },
    {
      title: 'First Person Lightning Roulette',
      category: 'rngeuropeanroulette',
      tableId: 'rng-rt-lightning',
      gameId: 'lcevo_1006megaball',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/tablegames/first-person-lightning-roulette.png'),
      range: '2 Đ - 40.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB
    },
    {
      title: 'First Person Roulette',
      category: 'rngeuropeanroulette',
      tableId: 'rng-rt-european0',
      gameId: 'lcevo_1006monopoly',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/tablegames/first-person-roulette.png'),
      range: '2 Đ - 40.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB
    },
    {
      title: 'First Person Mega Ball',
      category: 'rng-megaball',
      tableId: 'RngMegaBall00001',
      gameId: 'lcevo_1006rng-megaball',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/tablegames/first-person-mega-ball.png'),
      range: '2 Đ - 2.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB
    },
    {
      title: 'First Person Dream Catcher',
      category: 'rngmoneywheel',
      tableId: 'rng-dreamcatcher',
      gameId: 'lcevo_1006crazytime',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/tablegames/first-person-dream-catcher.png'),
      range: '2 Đ - 20.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB
    },
    {
      title: 'First Person Top Card',
      category: 'rng-topcard',
      tableId: 'rng-topcard00001',
      gameId: 'lcevo_1006rng-topcard',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/tablegames/first-person-top-card.png'),
      range: '4 Đ - 100.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB
    }
  ],
  dragontiger: [
    {
      title: 'Dragon Tiger',
      category: 'dragontiger',
      tableId: 'DragonTiger00001',
      gameId: 'lcevo_1006baccarat',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/dragontigers/dragon-tiger.png'),
      range: '20 Đ - 100.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB,
      feature: true
    },
    {
      title: 'Super Sic Bo',
      category: 'sicbo',
      tableId: 'SuperSicBo000001',
      gameId: 'lcevo_1006sicbo',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/dragontigers/super-sic-bo.png'),
      range: '4 Đ - 50.000 Đ',
      loginRequired: true,
      newTab: false,
      wallet: WALLET.SUB,
      feature: true
    }
  ],
  roulette: [
    {
      title: 'Speed Roulette',
      category: 'roulette',
      tableId: 'lkcbrbdckjxajdol',
      gameId: 'lcevo_1006roulette',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/roulettes/speed-roulette.png'),
      range: '10 Đ - 40.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB
    },
    {
      title: 'Roulette',
      category: 'roulette',
      tableId: 'vctlz20yfnmp1ylr',
      gameId: 'lcevo_1006roulette',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/roulettes/roulette.png'),
      range: '10 Đ - 40.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB,
      feature: true
    },
    {
      title: 'Immersive Roulette',
      category: 'roulette',
      tableId: '7x0b1tgh7agmf6hv',
      gameId: 'lcevo_1006blackjack',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/roulettes/immersive-roulette.png'),
      range: '20 Đ - 40.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB,
      feature: true
    },
    {
      title: 'Auto-Roulette',
      category: 'roulette',
      tableId: '48z5pjps3ntvqc1b',
      gameId: 'lcevo_1006roulette',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/roulettes/auto-roulette.png'),
      range: '2 Đ - 40.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB
    },
    {
      title: 'Instant Roulette',
      category: 'instantroulette',
      tableId: 'InstantRo0000001',
      gameId: 'lcevo_1006roulette',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/roulettes/instant-roulette.png'),
      range: '2 Đ - 40.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB,
      feature: true
    },
    {
      title: 'Instant Roulette',
      category: 'instantroulette',
      tableId: 'ojpo7pbp6fkkavv5',
      gameId: 'lcevo_1006roulette',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/roulettes/instant-roulette.png'),
      range: '2 Đ - 40.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB,
      isMobile: true
    },
    {
      title: 'VIP Roulette',
      category: 'roulette',
      tableId: 'wzg6kdkad1oe7m5k',
      gameId: 'lcevo_1006roulette',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/roulettes/vip-roulette.png'),
      range: '20 Đ - 40.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB
    },
    {
      title: 'French Roulette Gold',
      category: 'roulette',
      tableId: 'ojpt5cdx6fkkelnx',
      gameId: 'lcevo_1006blackjack',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/roulettes/french-roulette-gold.png'),
      range: '20 Đ - 40.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB
    },
    {
      title: 'American Roulette',
      category: 'americanroulette',
      tableId: 'AmericanTable001',
      gameId: 'lcevo_1006americanroulette',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/roulettes/american-roulette.png'),
      range: '4 Đ - 40.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB
    },
    {
      title: 'Double Ball Roulette',
      category: 'roulette',
      tableId: 'DoubleBallRou001',
      gameId: 'lcevo_1006megaball',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/roulettes/double-ball-roulette.png'),
      range: '4 Đ - 20.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB
    },
    {
      title: 'Speed Auto Roulette',
      category: 'roulette',
      tableId: 'SpeedAutoRo00001',
      gameId: 'lcevo_1006roulette',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/roulettes/speed-auto-roulette.png'),
      range: '2 Đ - 40.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB
    },
    {
      title: 'Auto-Roulette VIP',
      category: 'roulette',
      tableId: '01rb77cq1gtenhmo',
      gameId: 'lcevo_1006roulette',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/roulettes/auto-roulette-vip.png'),
      range: '4 Đ - 40.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB
    },
    {
      title: 'Auto-Roulette La Partage',
      category: 'roulette',
      tableId: 'f1f4rm9xgh4j3u2z',
      gameId: 'lcevo_1006roulette',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/roulettes/auto-roulette-la-partage.png'),
      range: '4 Đ - 40.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB
    },
    {
      title: 'Salon Prive Roulette',
      category: 'roulette',
      tableId: 'mdkqijp3dctrhnuv',
      gameId: 'lcevo_1006roulette',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/roulettes/salon-prive-roulette.png'),
      range: '2.000 Đ - 200.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB
    }
  ],
  blackjack: [
    {
      title: 'Blackjack A',
      category: 'blackjack',
      tableId: 'uwd2bl2khwcikjlz',
      gameId: 'lcevo_1006blackjack',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/blackjacks/blackjack-a.png'),
      range: '100 Đ - 20.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB
    },
    {
      title: 'Blackjack B',
      category: 'blackjack',
      tableId: 'xphpcthv8e6ivc16',
      gameId: 'lcevo_1006blackjack',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/blackjacks/blackjack-b.png'),
      range: '200 Đ - 20.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB
    },
    {
      title: 'Speed Blackjack K',
      category: 'blackjack',
      tableId: 'k4r2ejwx4eqqb6tv',
      gameId: 'lcevo_1006blackjack',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/blackjacks/speed-blackjack-k.png'),
      range: '200 Đ - 20.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB
    },
    {
      title: 'Blackjack Party',
      category: 'blackjack',
      tableId: 'sni5cza6d1vvl50i',
      gameId: 'lcevo_1006blackjack',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/blackjacks/blackjack-party.png'),
      range: '100 Đ - 20.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB
    },
    {
      title: 'Speed VIP Blackjack A',
      category: 'blackjack',
      tableId: 'SpeedBlackjack01',
      gameId: 'lcevo_1006blackjack',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/blackjacks/speed-vip-blackjack-a.png'),
      range: '1.000 Đ - 20.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB
    },
    {
      title: 'Speed VIP Blackjack B',
      category: 'blackjack',
      tableId: 'SpeedBlackjack02',
      gameId: 'lcevo_1006blackjack',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/blackjacks/speed-vip-blackjack-b.png'),
      range: '1.000 Đ - 20.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB
    },
    {
      title: 'Speed VIP Blackjack C',
      category: 'blackjack',
      tableId: 'SpeedBlackjack03',
      gameId: 'lcevo_1006blackjack',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/blackjacks/speed-vip-blackjack-c.png'),
      range: '1.000 Đ - 20.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB
    },
    {
      title: 'Speed VIP Blackjack D',
      category: 'blackjack',
      tableId: 'SpeedBlackjack04',
      gameId: 'lcevo_1006blackjack',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/blackjacks/speed-vip-blackjack-d.png'),
      range: '1.000 Đ - 20.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB
    },
    {
      title: 'Blackjack C',
      category: 'blackjack',
      tableId: 'jhs44mm0v3fi3aux',
      gameId: 'lcevo_1006blackjack',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/blackjacks/blackjack-c.png'),
      range: '300 Đ - 20.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB
    },
    {
      title: 'Speed Blackjack L',
      category: 'blackjack',
      tableId: 'k4r2hyhw4eqqb6us',
      gameId: 'lcevo_1006blackjack',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/blackjacks/speed-blackjack-l.png'),
      range: '300 Đ - 20.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB
    },
    {
      title: 'Speed Blackjack D',
      category: 'blackjack',
      tableId: 'xqyb2u7fqkexxpa0',
      gameId: 'lcevo_1006blackjack',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/blackjacks/speed-blackjack-d.png'),
      range: '400 Đ - 20.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB
    },
    {
      title: 'Speed Blackjack M',
      category: 'blackjack',
      tableId: 'k4r2kvd34eqqb6vh',
      gameId: 'lcevo_1006blackjack',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/blackjacks/speed-blackjack-m.png'),
      range: '400 Đ - 20.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB
    },
    {
      title: 'Speed Blackjack E',
      category: 'blackjack',
      tableId: 'ylq4gmw8yl22u5dj',
      gameId: 'lcevo_1006blackjack',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/blackjacks/speed-blackjack-e.png'),
      range: '500 Đ - 20.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB
    },
    {
      title: 'Blackjack VIP X',
      category: 'blackjack',
      tableId: 'bghflgi59db7d7r2',
      gameId: 'lcevo_1006blackjack',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/blackjacks/blackjack-vip-x.png'),
      range: '2.000 Đ - 20.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB
    },
    {
      title: 'Speed Blackjack G',
      category: 'blackjack',
      tableId: '1xwfnktjybsolkn6',
      gameId: 'lcevo_1006blackjack',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/blackjacks/blackjack-vip-g.png'),
      range: '500 Đ - 20.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB
    },
    {
      title: 'Speed Blackjack H',
      category: 'blackjack',
      tableId: 'nc3u2l6y0khszjv7',
      gameId: 'lcevo_1006blackjack',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/blackjacks/speed-blackjack-h.png'),
      range: '500 Đ - 20.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB
    },
    {
      title: 'Speed Blackjack I',
      category: 'blackjack',
      tableId: 'xstnlyzrm345ev95',
      gameId: 'lcevo_1006blackjack',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/blackjacks/speed-blackjack-i.png'),
      range: '700 Đ - 20.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB
    },
    {
      title: 'Speed Blackjack J',
      category: 'blackjack',
      tableId: 'i5j1cyqhrypkih23',
      gameId: 'lcevo_1006blackjack',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/blackjacks/speed-blackjack-j.png'),
      range: '700 Đ - 20.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB
    },
    {
      title: 'Blackjack Silver A',
      category: 'blackjack',
      tableId: 'gkmq0o2hryjyqu30',
      gameId: 'lcevo_1006blackjack',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/blackjacks/blackjack-silver-a.png'),
      range: '1.000 Đ - 20.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB
    },
    {
      title: 'Blackjack Silver B',
      category: 'blackjack',
      tableId: '9f4xhuhdd005xlbl',
      gameId: 'lcevo_1006blackjack',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/blackjacks/blackjack-silver-b.png'),
      range: '1.000 Đ - 20.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB
    },
    {
      title: 'Blackjack Silver C',
      category: 'blackjack',
      tableId: 'qlrc3fq3v7p6awm4',
      gameId: 'lcevo_1006blackjack',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/blackjacks/blackjack-silver-c.png'),
      range: '1.000 Đ - 20.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB
    },
    {
      title: 'Blackjack Silver D',
      category: 'blackjack',
      tableId: 'qckwjf2o52r9ikeb',
      gameId: 'lcevo_1006blackjack',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/blackjacks/blackjack-silver-d.png'),
      range: '1.000 Đ - 20.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB
    },
    {
      title: 'Blackjack Silver E',
      category: 'blackjack',
      tableId: 'gazgtkid9h1b0dn9',
      gameId: 'lcevo_1006blackjack',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/blackjacks/blackjack-silver-e.png'),
      range: '1.000 Đ - 20.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB
    },
    {
      title: 'Blackjack Silver F',
      category: 'blackjack',
      tableId: 'lnofoyxv756qaezy',
      gameId: 'lcevo_1006blackjack',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/blackjacks/blackjack-silver-f.png'),
      range: '1.000 Đ - 20.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB
    },
    {
      title: 'Blackjack Silver G',
      category: 'blackjack',
      tableId: 'lnofpmm3756qae2c',
      gameId: 'lcevo_1006blackjack',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/blackjacks/blackjack-silver-g.png'),
      range: '1.000 Đ - 20.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB
    },
    {
      title: 'Blackjack VIP A',
      category: 'blackjack',
      tableId: '0mvn914lkmo9vaq8',
      gameId: 'lcevo_1006blackjack',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/blackjacks/blackjack-vip-a.png'),
      range: '2.000 Đ - 20.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB
    },
    {
      title: 'Blackjack VIP B',
      category: 'blackjack',
      tableId: 'cpxl81x0rgi34cmo',
      gameId: 'lcevo_1006blackjack',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/blackjacks/blackjack-vip-b.png'),
      range: '2.000 Đ - 20.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB
    },
    {
      title: 'Blackjack VIP C',
      category: 'blackjack',
      tableId: 'l5aug44hhzr3qvxs',
      gameId: 'lcevo_1006blackjack',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/blackjacks/blackjack-vip-c.png'),
      range: '5.000 Đ - 20.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB
    },
    {
      title: 'Blackjack VIP D',
      category: 'blackjack',
      tableId: 'o3d9tx3u8kd0yawc',
      gameId: 'lcevo_1006blackjack',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/blackjacks/blackjack-vip-d.png'),
      range: '2.000 Đ - 20.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB
    },
    {
      title: 'Blackjack VIP E',
      category: 'blackjack',
      tableId: 'psm2um7k4da8zwc2',
      gameId: 'lcevo_1006blackjack',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/blackjacks/blackjack-vip-e.png'),
      range: '2.000 Đ - 20.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB
    },
    {
      title: 'Blackjack VIP G',
      category: 'blackjack',
      tableId: 'z5pf5pichcsw3d2o',
      gameId: 'lcevo_1006blackjack',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/blackjacks/blackjack-vip-g.png'),
      range: '2.000 Đ - 20.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB
    },
    {
      title: 'Blackjack VIP H',
      category: 'blackjack',
      tableId: 's63nx2mpdomgjagb',
      gameId: 'lcevo_1006blackjack',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/blackjacks/blackjack-vip-h.png'),
      range: '2.000 Đ - 20.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB
    },
    {
      title: 'Blackjack VIP I',
      category: 'blackjack',
      tableId: 'lnofn2yl756qaezm',
      gameId: 'lcevo_1006blackjack',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/blackjacks/blackjack-vip-i.png'),
      range: '5.000 Đ - 20.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB
    },
    {
      title: 'Blackjack VIP L',
      category: 'blackjack',
      tableId: 'nbjettfehawanhes',
      gameId: 'lcevo_1006blackjack',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/blackjacks/blackjack-vip-l.png'),
      range: '2.000 Đ - 20.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB
    },
    {
      title: 'Blackjack VIP M',
      category: 'blackjack',
      tableId: 'nbjetztthawanhey',
      gameId: 'lcevo_1006blackjack',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/blackjacks/blackjack-vip-m.png'),
      range: '1.000 Đ - 20.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB
    },
    {
      title: 'Blackjack VIP O',
      category: 'blackjack',
      tableId: 'nkyivihc2jpbw4uy',
      gameId: 'lcevo_1006blackjack',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/blackjacks/blackjack-vip-o.png'),
      range: '1.000 Đ - 20.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB
    },
    {
      title: 'Blackjack VIP P',
      category: 'blackjack',
      tableId: 'nsxqkywul2nzcwwh',
      gameId: 'lcevo_1006blackjack',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/blackjacks/blackjack-vip-p.png'),
      range: '1.000 Đ - 20.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB
    },
    {
      title: 'Blackjack VIP Q',
      category: 'blackjack',
      tableId: 'oa7fvyaiqfueq5ob',
      gameId: 'lcevo_1006blackjack',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/blackjacks/blackjack-vip-q.png'),
      range: '2.000 Đ - 20.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB
    },
    {
      title: 'Blackjack VIP R',
      category: 'blackjack',
      tableId: 'nsxqpyiol2nzcz6t',
      gameId: 'lcevo_1006blackjack',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/blackjacks/blackjack-vip-r.png'),
      range: '10.000 Đ - 20.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB
    },
    {
      title: 'Blackjack VIP S',
      category: 'blackjack',
      tableId: 'nveq65dtmn6n4mnd',
      gameId: 'lcevo_1006blackjack',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/blackjacks/blackjack-vip-s.png'),
      range: '1.000 Đ - 20.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB
    },
    {
      title: 'Blackjack VIP T',
      category: 'blackjack',
      tableId: 'nveq66tfmn6n4moi',
      gameId: 'lcevo_1006blackjack',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/blackjacks/blackjack-vip-t.png'),
      range: '1.000 Đ - 20.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB
    },
    {
      title: 'Blackjack Platinum VIP',
      category: 'blackjack',
      tableId: 'h463tlq1rhl1lfr2',
      gameId: 'lcevo_1006blackjack',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/blackjacks/blackjack-platinum-vip.png'),
      range: '5.000 Đ - 20.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB
    },
    {
      title: 'Blackjack Fortune VIP',
      category: 'blackjack',
      tableId: 'ejx1a04w4ben0mou',
      gameId: 'lcevo_1006blackjack',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/blackjacks/blackjack-fortune-vip.png'),
      range: '5.000 Đ - 20.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB
    },
    {
      title: 'Blackjack Grand VIP',
      category: 'blackjack',
      tableId: 'gfzrqe4hqv24kukc',
      gameId: 'lcevo_1006blackjack',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/blackjacks/blackjack-grand-vip.png'),
      range: '10.000 Đ - 50.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB
    },
    {
      title: 'Blackjack Diamond VIP',
      category: 'blackjack',
      tableId: 'rdefcn4sffgo39l7',
      gameId: 'lcevo_1006blackjack',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/blackjacks/blackjack-diamond-vip.png'),
      range: '20.000 Đ - 50.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB
    },
    {
      title: 'Salon Prive Blackjack A',
      category: 'blackjack',
      tableId: 'mdkqdxtkdctrhnsx',
      gameId: 'lcevo_1006blackjack',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/blackjacks/salon-prive-blackjack-a.png'),
      range: '20.000 Đ - 200.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB
    },
    {
      title: 'Salon Prive Blackjack B',
      category: 'blackjack',
      tableId: 'olbibp3fylzaxvhb',
      gameId: 'lcevo_1006blackjack',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/blackjacks/salon-prive-blackjack-b.png'),
      range: '20.000 Đ - 200.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB
    },
    {
      title: 'Salon Prive Blackjack C',
      category: 'blackjack',
      tableId: 'mdkqfe74dctrhntj',
      gameId: 'lcevo_1006blackjack',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/blackjacks/salon-prive-blackjack-c.png'),
      range: '20.000 Đ - 200.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB
    },
    {
      title: 'Salon Prive Blackjack D',
      category: 'blackjack',
      tableId: 'olbinkuoylzayeoj',
      gameId: 'lcevo_1006blackjack',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/blackjacks/salon-prive-blackjack-d.png'),
      range: '30.000 Đ - 200.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB
    }
  ],
  poker: [
    {
      title: 'Caribbean Stud Poker',
      category: 'csp',
      tableId: 'CSPTable00000001',
      gameId: 'lcevo_1006csp',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/pokers/caribbean-stud-poker.png'),
      range: '20 Đ - 20.000 Đ',
      loginRequired: true,
      newTab: false,
      wallet: WALLET.SUB
    },
    {
      title: 'Casino Hold\'em',
      category: 'holdem',
      tableId: 'HoldemTable00001',
      gameId: 'lcevo_1006holdem',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/pokers/casino-holdem.png'),
      range: '10 Đ - 20.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB,
      feature: true
    },
    {
      title: '2 Hand Casino Hold\'em',
      category: 'dhp',
      tableId: 'DHPTable00000001',
      gameId: 'lcevo_1006dhp',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/pokers/2-hand-casino-holdem.png'),
      range: '10 Đ - 20.000 Đ',
      loginRequired: true,
      newTab: false,
      wallet: WALLET.SUB
    },
    {
      title: 'Extreme Texas Hold\'em',
      category: 'eth',
      tableId: 'ETHTable00000001',
      gameId: 'lcevo_1006eth',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/pokers/extreme-texas-holdem.png'),
      range: '10 Đ - 5.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB
    },
    {
      title: 'Triple Card Poker',
      category: 'trp',
      tableId: 'TRPTable00000001',
      gameId: 'lcevo_1006trp',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/pokers/triple-card-poker.png'),
      range: '20 Đ - 20.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB
    },
    {
      title: 'Texas Hold\'em Bonus Poker',
      category: 'thb',
      tableId: 'THBTable00000001',
      gameId: 'lcevo_1006thb',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/pokers/texas-holdem-bonus-poker.png'),
      range: '10 Đ - 10.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB
    },
    {
      title: 'Side Bet City',
      category: 'sidebetcity',
      tableId: 'SBCTable00000001',
      gameId: 'lcevo_1006sidebetcity',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/pokers/side-bet-city.png'),
      range: '10 Đ - 10.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB
    }
  ],
  gameshow: [
    {
      title: 'Crazy Time',
      category: 'crazytime',
      tableId: 'CrazyTime0000001',
      gameId: 'lcevo_1006crazytime',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/gameshows/crazy-time.png'),
      range: '2 Đ - 20.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB,
      feature: true
    },
    {
      title: 'Mega Ball',
      category: 'megaball',
      tableId: 'MegaBall00000001',
      gameId: 'lcevo_1006megaball',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/gameshows/mega-ball.png'),
      range: '2 Đ - 2.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB,
      feature: true
    },
    {
      title: 'MONOPOLY Live',
      category: 'monopoly',
      tableId: 'Monopoly00000001',
      gameId: 'lcevo_1006monopoly',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/gameshows/monopoly-live.png'),
      range: '2 Đ - 20.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB,
      feature: true
    },
    {
      title: 'Deal or No Deal',
      category: 'dealnodeal',
      tableId: 'dealnodeal000001',
      gameId: 'lcevo_1006dealnodeal',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/gameshows/deal-or-no-deal.png'),
      range: '2 Đ - 18.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB
    },
    {
      title: 'Lightning Roulette',
      category: 'roulette',
      tableId: 'LightningTable01',
      gameId: 'lcevo_1006roulette',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/gameshows/lightning-roulette.png'),
      range: '4 Đ - 40.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB,
      feature: true
    },
    {
      title: 'Dream Catcher',
      category: 'moneywheel',
      tableId: 'MOWDream00000001',
      gameId: 'lcevo_1006moneywheel',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/gameshows/dream-catcher.png'),
      range: '2 Đ - 20.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB,
      feature: true
    },
    {
      title: 'Lightning Dice',
      category: 'lightningdice',
      tableId: 'LightningDice001',
      gameId: 'lcevo_1006lightningdice',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/gameshows/lightning-dice.png'),
      range: '4 Đ - 10.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB
    },
    {
      title: 'Football studio',
      category: 'topcard',
      tableId: 'TopCard000000001',
      gameId: 'lcevo_1006topcard',
      imgSrc: require('~imageAsset/lobby/lobby-casino-item/gameshows/football-studio.png'),
      range: '20 Đ - 100.000 Đ',
      loginRequired: true,
      provider: 'Evolution',
      newTab: false,
      wallet: WALLET.SUB,
      feature: true
    }
  ]
}

Object.keys(lobbyCasino).forEach((index) => {
  const value = lobbyCasino[index].filter(function (game) {
    return game.feature === true
  })
  lobbyCasino.hotgame.push(...value)
})

export { lobbyCasino }
