export const META_TITLES = {
  index: 'Nhà cái MU9 - Nhà cái cá cược bóng đá, cá độ thể thao uy tín số #1 Anh Quốc',
  'live-sports': 'Thể Thao MU9',
  esports: 'E-Sports MU9',
  'virtual-sports': 'Virtual Sports MU9',
  'live-casino': 'Live casino MU9',
  lobby: 'Cổng Game MU9',
  've-chung-toi': {
    've-chung-toi': 'Về Chúng tôi MU9',
    'dieu-khoan-dieu-kien': 'Điều khoản và điều kiện MU9',
    'chinh-sach-bao-mat': 'Chính sách bảo mật MU9',
    'khuyen-mai': 'Khuyến mãi MU9',
    'phuong-thuc-thanh-toan': 'Phương thức thanh toán MU9',
    default: 'Về Chúng tôi MU9'
  },
  faq: 'Câu hỏi thường gặp MU9',
  'lien-he': 'Liên hệ MU9',
  'tin-tuc': 'Tin Tức MU9',
  keno: 'Keno MU9',
  lottery: 'Lottery MU9',
  numbergame: 'Numbers Game MU9',
  'saba-club': 'Saba Games MU9',
  tablegame: 'Table Games MU9',
  virtualgame: 'Virtual Games MU9',
  'tp-keno': 'Keno TP MU9',
  'tp-numbergame': 'Numbers Game TP MU9',
  account: {
    'account-info': 'Thông tin tài khoản MU9',
    'account-info-info-personal': 'Thông tin tài khoản MU9',
    'account-info-info-bank': 'Thông tin ngân hàng MU9',
    'history-transaction': 'Lịch sử giao dịch MU9',
    'history-betting': 'Lịch sử cá cược MU9',
    'history-betting-betting': 'Lịch sử cá cược MU9',
    'history-betting-sport': 'Lịch sử game ví phụ MU9',
    deposit: 'Nạp tiền MU9',
    withdraw: 'Rút tiền MU9',
    default: 'Tài khoản MU9'
  },
  default: 'Nhà cái MU9 - Nhà cái cá cược bóng đá, cá độ thể thao uy tín số #1 Anh Quốc'
}
